version: '3.7'

services:
  django:
    build: ./artway
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
    volumes:
      - static:/usr/src/artway/static
      - /home/artway:/usr/src/artway
    expose:
      - 8080
  nginx:
    build: ./nginx
    command: nginx -g "daemon off;"
    volumes:
      - static:/usr/src/artway/static
      - /home/artway:/usr/src/artway
    ports:
      - 8000:80
    depends_on:
      - django
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=artway_user
      - POSTGRES_PASSWORD=P98KVAWdkmrgi324
      - POSTGRES_DB=artway_db
volumes:
  static:
  postgres_data: