version: '3.7'

services:
  django:
    build: ./artway
    command: gunicorn --bind 0.0.0.0:8080 project.wsgi
    volumes:
      - static:/usr/src/ARTWAY-PROJECT/static
      - /home/artway:/usr/src/ARTWAY-PROJECT
    expose:
      - 8080
  nginx:
    build: ./nginx
    command: nginx -g "daemon off;"
    volumes:
      - static:/usr/src/ARTWAY-PROJECT/static
      - /home/artway:/usr/src/ARTWAY-PROJECT
    ports:
      - 8000:80
    depends_on:
      - django
volumes:
  static:
