# Generated by Django 3.1.2 on 2020-12-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='audio',
            field=models.FileField(blank=True, upload_to='Artifact audios', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Artifact photos', verbose_name='Фотография'),
        ),
    ]
