# Generated by Django 3.1.2 on 2020-12-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201212_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Описание'),
        ),
    ]
