# Generated by Django 3.1.2 on 2020-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201214_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='Artifact QR-codes', verbose_name='QR code'),
        ),
    ]
