# Generated by Django 3.1.2 on 2021-01-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_museum_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='admins',
        ),
        migrations.AddField(
            model_name='user',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='main_app.museum', verbose_name='Сузей'),
        ),
    ]
