# Generated by Django 3.1.2 on 2021-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_artifact_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='next_artifact',
            field=models.IntegerField(null=True, verbose_name='Следующий экспонат'),
        ),
    ]
