# Generated by Django 3.1.2 on 2021-01-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210115_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='main_app.museum', verbose_name='Музей'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Artifact photos', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
                ('museum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location', to='main_app.museum', verbose_name='Музей')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
