# Generated by Django 3.1.2 on 2021-01-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_artifact_next_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='prev_artifact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий экспонат'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='next_artifact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Следующий экспонат'),
        ),
    ]
