# Generated by Django 3.1.2 on 2021-01-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210115_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='main_app.museum', verbose_name='Музей'),
        ),
    ]
