# Generated by Django 3.1.2 on 2021-01-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210114_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='prev_artifact',
        ),
    ]
