# Generated by Django 3.1.2 on 2021-01-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_artifact_prev_artifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='next_artifact',
        ),
        migrations.AddField(
            model_name='artifact',
            name='prev_artifact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предыдущий экспонат'),
        ),
    ]
