# Generated by Django 3.1.2 on 2021-01-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210115_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='halls', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
                ('prev', models.IntegerField(blank=True, null=True, verbose_name='Зал выше')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halls', to='main_app.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
    ]
