# Generated by Django 3.1.2 on 2021-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_artifact_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('service_super_admin', 'Супер-админ сервиса'), ('museum_super_admin', 'Супер-админ музея'), ('museum_admin', 'Админ музея'), ('museum_cashier', 'Кассир музея')], default='none', max_length=64, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
    ]
