# Generated by Django 3.1.2 on 2021-01-19 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210118_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='ticket_lifetime',
            field=models.IntegerField(default=3, verbose_name='Время действия билета'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, verbose_name='Токен')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('museum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main_app.museum', verbose_name='Билет')),
            ],
        ),
    ]
