# Generated by Django 3.1.2 on 2021-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210119_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(blank=True, upload_to='tickets', verbose_name='PDF'),
        ),
    ]
