# Generated by Django 3.1.5 on 2021-01-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_artifact_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='main_app.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='main_app.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='location',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main_app.museum', verbose_name='Музей'),
        ),
    ]
