# Generated by Django 3.1.5 on 2021-01-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210123_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='img',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='img',
        ),
    ]
