# Generated by Django 3.1.5 on 2021-02-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210130_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='museum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='main_app.museum', verbose_name='Музей'),
        ),
    ]
