# Generated by Django 3.1.5 on 2021-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_artifactlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactlink',
            name='link',
            field=models.CharField(default=0, max_length=1000, verbose_name='Ссылки'),
            preserve_default=False,
        ),
    ]
