# Generated by Django 3.1.5 on 2021-02-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_artifactlink_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='img',
        ),
        migrations.AddField(
            model_name='artifact',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/photos', verbose_name='Фотография #1'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/photos', verbose_name='Фотография #2'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/photos', verbose_name='Фотография #3'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/photos', verbose_name='Фотография #4'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='artifacts/photos', verbose_name='Фотография #5'),
        ),
        migrations.DeleteModel(
            name='ArtifactLink',
        ),
    ]
