# Generated by Django 3.1.5 on 2021-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210224_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='audio',
        ),
        migrations.AddField(
            model_name='artifact',
            name='audio_1',
            field=models.FileField(blank=True, upload_to='artifacts/audios', verbose_name='Аудио #1'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='audio_2',
            field=models.FileField(blank=True, upload_to='artifacts/audios', verbose_name='Аудио #2'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='audio_3',
            field=models.FileField(blank=True, upload_to='artifacts/audios', verbose_name='Аудио #3'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='audio_4',
            field=models.FileField(blank=True, upload_to='artifacts/audios', verbose_name='Аудио #4'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='audio_5',
            field=models.FileField(blank=True, upload_to='artifacts/audios', verbose_name='Аудио #5'),
        ),
    ]
