# Generated by Django 3.1.5 on 2021-02-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20210225_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='video',
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_name_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название ссылки #1'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_name_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название ссылки #2'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_name_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название ссылки #3'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_name_4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название ссылки #4'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_name_5',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название ссылки #5'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_value_1',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка #1'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_value_2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка #2'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_value_3',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка #3'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_value_4',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка #4'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='link_value_5',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка #5'),
        ),
    ]
